typography_spectrum: 0.20784
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#919191'
    - '#c2c2c2'
    - '#484848'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.75
  rhythmicContrast: 0
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.57112
analytics:
  google: null
  facebook: null
  twitter: null
name: Letters to NYC
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Letters to NYC
description: your favorite love story.
purpose: []
